---
version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      # TODO: Replace the app mappings to the linux/windows host
      - ./.compose/plex/library:/config
      - ./.compose/plex/tvseries:/tv
      - ./.compose/plex/movies:/movies
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/Brisbane
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      # TODO: Replace the app mappings to the linux/windows host
      - ./.compose/overseerr/config:/app/config
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./.compose/prowlerr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./.compose/radarr/config:/config
      - ./.compose/plex/movies:/movies #optional
      - ./.compose/shared/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./.compose/sonarr/config:/config
      - ./.compose/plex/tvseries:/tv #optional
      - ./.compose/shared/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./.compose/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - WEBUI_PORT=8080
    volumes:
      - ./.compose/qbittorent/config:/config
      - ./.compose/shared/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
# TODO: Enable once hosted correctly
#    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./.compose/homeassistant/config:/config
    ports:
      - 8123:8123 #optional
#    devices:
#      - ./.compose/homeassistant/device/:/path/to/device #optional
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./.compose/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./.compose/bazarr/config:/config
      - ./.compose/plex/movies:/movies #optional
      - ./.compose/plex/tvseries:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  # https://github.com/meisnate12/Plex-Meta-Manager
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      - ./.compose/plex-meta-manager/config:/config
    restart: unless-stopped