---
version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      # TODO: Replace the app mappings to the linux/windows host
      - ./plex/library:/config
      - ./plex/tvseries:/tv
      - ./plex/movies:/movies
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/Brisbane
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      # TODO: Replace the app mappings to the linux/windows host
      - ./overseerr/config:/app/config
    restart: unless-stopped